### ISSUE TITLE
Installation Error - Apple M1

### ISSUE THREAD

**Issue by XiuzhenChen** [samgould2/PEGG2.0#1]
On a Apple M1, clean miniconda installation, the installation fails:

```
conda create -n pegg python=3.9
conda activate pegg

pip install pegg

Collecting pegg
  Using cached pegg-2.0.9-py3-none-any.whl.metadata (777 bytes)
Collecting Bio>=1.4.0 (from pegg)
  Using cached bio-1.6.2-py3-none-any.whl.metadata (5.1 kB)
Collecting cyvcf2>=0.30.18 (from pegg)
  Using cached cyvcf2-0.30.28.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Users/xchen/miniconda3/envs/pegg/lib/pypy3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/xchen/miniconda3/envs/pegg/lib/pypy3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/xchen/miniconda3/envs/pegg/lib/pypy3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 20, in <module>
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/numpy/__init__.py", line 139, in <module>
          from . import core
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
          from . import multiarray
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/numpy/core/multiarray.py", line 86, in <module>
          def empty_like(prototype, dtype=None, order=None, subok=None, shape=None):
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 178, in decorator
          return array_function_dispatch(
        File "/private/var/folders/wd/fbq9qwjn77l2c5k4wkzh5xqr0000gq/T/pip-build-env-fjbh4n5m/overlay/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 160, in decorator
          public_api = _ArrayFunctionDispatcher(dispatcher, implementation)
      AttributeError: 'builtin_function_or_method' object has no attribute '__qualname__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

What do you advise I try?

**Comment by samgould2** [comment]
Hi, this seems to be an issue with the cyvcf2 package (this package is just used for translating ClinVar IDs to a useable format). I see that you're already using a virtual environment. The simplest thing is to install and use PEGG in Google Colab if this issue persists (obviously not ideal). If you want to run it locally, and this issue persists, you should be able to download the repository and just import the pertinent python scripts, as opposed to pip installing the package (also not ideal). I'm working on stabilizing the installation issue and making it amenable to later python versions.

**Comment by samgould2** [comment]
It seems that the cyvcf2 package was updated recently (Jan 2024). This is likely the issue. A potential solution is installing cyvcf==0.30.18 in the virtual environment first (as opposed to 0.30.28). This could fix the issue. Let me know.

**Comment by samgould2** [comment]
I've packaged a version of PEGG that excludes the cyvcf2 file. It can be accessed at the following dropbox link: https://www.dropbox.com/sh/5xsdzyiyrjiu9pf/AADiFFA3BQ3vX7swja-i2NBqa?dl=0 (it's pegg-2.0.92-py3-none-any.whl). You should be able to install this in your virtual environment using the normal pip install command:

`pip install pegg-2.0.92-py3-none-any.whl`

This only removes the functionality of translate ClinVar IDs to a format compatible with PEGG. All other functions remain unchanged. Let me know if this fixes the issue.
